import { createVo2Content } from '../content-factory';

export const content = createVo2Content({
  locale: 'ko', slug: 'vo2-max-calculator', title: '달리기 걷기 비프 테스트용 VO2 max 계산기', description: '12분 달리기, 1.5마일 달리기, 록포트 걷기 테스트 또는 20미터 셔틀 테스트로 VO2 max를 추정하고 연령과 성별 기준과 비교합니다.', faqTitle: 'VO2 max 계산기 질문', bibliographyTitle: '추정값의 근거가 된 세 가지 자료', diagnosticBadge: '알아둘 점',
  ui: {
    methodCooper12: '쿠퍼 12분 달리기', methodCooper15: '쿠퍼 1.5마일 달리기', methodRockport: '록포트 1마일 걷기', methodShuttle: '20미터 셔틀 테스트', metricUnit: '미터법', imperialUnit: '야드 파운드법', methodLabel: '필드 테스트', performanceLegend: '기록한 결과', distanceLabel: '12분 동안 이동한 거리', distanceHint: '측정된 코스에서 12분 동안 최대한 멀리 달립니다.', timeLabel: '테스트 시간', minutesLabel: '분', secondsLabel: '초', ageLabel: '나이', sexLabel: '참조 성별', maleLabel: '남성', femaleLabel: '여성', weightLabel: '체중', heartRateLabel: '테스트 종료 심박수', stageLabel: '마지막으로 완료한 단계', stageHint: '1에서 21 사이의 마지막 완전 완료 단계를 입력하세요.', resetButton: '예시 복원', resultTitle: '추정 VO2 max', estimateUnit: '분당 체중 1kg당 산소 ml', percentileLabel: '참조 구간', referenceTitle: '연령 및 성별 참조', referenceDescription: '그래프는 20세에서 79세 성인의 모집단 참조이며 의학적 분류가 아닙니다.', bandBelow10: '10백분위수 미만', band10to25: '10에서 25백분위수', band25to50: '25에서 50백분위수', band50to75: '50에서 75백분위수', band75to90: '75에서 90백분위수', bandAbove90: '90백분위수 초과', methodNoteCooper12: '이동한 거리로 계산한 쿠퍼 추정값입니다.', methodNoteCooper15: '1.5마일 달리기 시간으로 계산한 추정값입니다.', methodNoteRockport: '1마일 걷기 프로토콜로 계산한 록포트 추정값입니다.', methodNoteShuttle: '마지막 단계 속도로 계산한 셔틀 테스트 추정값입니다.', invalidNotice: '추정값을 보려면 이 테스트의 항목을 입력하세요.', safetyNotice: '필드 테스트는 임상 측정이 아닌 추정값입니다. 몸이 불편하면 중단하고 필요할 때 전문가의 안내를 받으세요.',
  },
  faq: [{ question: '달리기로 VO2 max를 어떻게 계산하나요?', answer: '쿠퍼 12분 달리기를 선택하고 이동한 거리를 입력하거나 1.5마일 달리기를 선택하고 시간을 입력하세요. 두 방법 모두 체중 1kg당 분당 산소 ml 단위의 추정값을 제공합니다.' }, { question: '쿠퍼 VO2 max 계산기는 어떻게 사용하나요?', answer: '측정된 코스에서 12분 동안 최대한 멀리 달리고 거리를 기록하세요. 결과를 비교할 때 같은 코스, 준비 운동, 측정 방법을 사용하세요.' }, { question: '록포트 걷기 테스트로 VO2 max를 계산할 수 있나요?', answer: '가능합니다. 1마일 걷기를 선택하고 시간, 체중, 나이, 참조 성별, 종료 심박수를 입력하세요. 이 프로토콜에는 안정시 심박수를 사용하지 마세요.' }, { question: '비프 테스트용 VO2 max 계산기로 사용할 수 있나요?', answer: '가능합니다. 20미터 셔틀 테스트를 선택하고 오디오에서 마지막으로 완전히 완료한 단계를 입력하세요. 결과는 거리, 속도, 단계 규칙에 따라 달라집니다.' }, { question: '나이 성별 체중별로 VO2 max를 비교할 수 있나요?', answer: '나이를 입력하고 참조 성별을 선택하면 추정값을 기준값과 비교할 수 있습니다. 체중은 록포트 공식에 사용됩니다. 이 비교는 모집단 맥락이지 진단이 아닙니다.' }, { question: '자전거 로잉 Garmin Apple Watch 안정시 심박수에도 사용할 수 있나요?', answer: '첫 버전에서는 지원하지 않습니다. 이 도구는 달리기, 걷기, 20미터 비프 테스트를 지원합니다. 자전거, 로잉, 웨어러블, 안정시 심박수에는 다른 데이터와 공식이 필요합니다.' }],
  howTo: [{ name: '맞는 테스트 선택', text: '기록한 결과에 맞는 달리기, 걷기 또는 셔틀 테스트 프로토콜을 선택하세요.' }, { name: '측정 결과 입력', text: '선택한 프로토콜에 필요한 경우에만 거리, 시간, 마지막 단계, 체중, 종료 심박수를 입력하세요.' }, { name: '나이와 성별 추가', text: '20세에서 79세 성인의 FRIEND 기준과 비교하려면 나이와 참조 성별을 입력하세요.' }, { name: '같은 프로토콜 반복', text: '다음 추정값을 비교하기 전에 같은 코스, 단위, 측정 절차를 사용하세요.' }],
  seo: {
    introTitle: '이미 가진 VO2 max 테스트에서 시작하세요', introParagraph: 'VO2 max 숫자는 출처를 알아야 유용합니다. 12분 달리기, 1마일 걷기, 비프 테스트는 서로 바꿔 쓸 수 있는 측정이 아닙니다. 이 계산기는 테스트를 보여 주고 알맞은 추정식을 사용하며 필드 테스트를 실험실 측정처럼 포장하지 않고 기준점을 제공합니다.', summaryTitle: '이 계산기는 무엇을 알려 주나요?', summaryItems: ['쿠퍼 12분 또는 1.5마일 달리기 결과 해석.', '록포트 1마일 걷기 결과 추정.', '20미터 비프 테스트의 마지막 완료 단계 사용.', '20세에서 79세 성인의 연령 및 성별 비교.', '자신의 변화를 추적할 반복 가능한 기준 만들기.'], stats: [{ value: '4', label: '필드 프로토콜' }, { value: '20에서 79', label: '참조 연령' }, { value: 'ml/kg/min', label: '공통 단위' }], protocolTitle: '공식보다 먼저 측정한 결과를 확인하세요', comparative: [{ title: '거리를 측정한 경우', description: '12분 동안 이동한 거리를 기록했다면 쿠퍼 12분 테스트를 선택하세요. 매번 같은 측정 코스와 단위를 사용하세요.' }, { title: '시간을 측정한 경우', description: '거리를 완주한 시간을 기록했다면 1.5마일 달리기를 선택하세요. 5K 시간이나 시계 추정값은 다른 계산에 해당합니다.' }], rockportTitle: '록포트 걷기 테스트에 더 많은 맥락이 필요한 이유', diagnosticTitle: '록포트 입력값을 작은 이야기로 읽기', diagnosticHtml: '<p>걷기는 최대하 운동이므로 그 1마일이 얼마나 힘들었는지에 대한 맥락이 공식에 필요합니다.</p><ul><li><strong>시간:</strong> 1마일을 완료하는 데 걸린 시간.</li><li><strong>종료 심박수:</strong> 안정시가 아닌 도착 시 심박수.</li><li><strong>체중, 나이, 성별:</strong> 공식과 참조값에 사용되는 맥락.</li></ul>', ageTitle: '같은 숫자도 나이에 따라 다른 이야기가 됩니다', tableHeaders: ['알고 싶은 것', '그래프가 알려 줄 수 있는 것', '그래프가 알려 줄 수 없는 것'], tableRows: [['추정값의 위치', '연령 및 성별 그룹 안의 구간.', '건강한지 또는 의학적으로 건강한지.'], ['훈련이 변화를 만들었는지', '같은 테스트를 반복했을 때의 추세.', '프로토콜이 바뀐 경우의 공정한 비교.'], ['이벤트를 준비했는지', '체력 맥락의 한 부분.', '경기 예측 또는 운동 허가.']], shuttleTitle: '비프 테스트에서는 코스와 함께해야 단계가 의미 있습니다', shuttleParagraph: '마지막 완료 단계는 보편적인 체력 단위가 아닙니다. 20미터 거리, 오디오, 회전 방식, 바닥, 단계 규칙이 중요합니다. 결과 변화에 의미를 주려면 같은 프로토콜을 반복하세요.', listItems: ['<strong>방법 반복:</strong> 달리기를 록포트 걷기와 비교하지 말고 쿠퍼를 쿠퍼와 비교하세요.', '<strong>조건 기록:</strong> 바닥, 날씨, 준비 운동, 심박수 측정 절차를 기록하세요.', '<strong>추세 확인:</strong> 하나의 추정값은 흔들릴 수 있으니 비교 가능한 여러 테스트를 보세요.', '<strong>구간은 조심스럽게 사용:</strong> 참조 맥락이지 몸에 대한 판정이 아닙니다.'], tipTitle: '자전거 로잉 또는 시계를 검색한 경우', tipHtml: '그것은 입력값이 빠진 것이 아니라 다른 질문입니다. 자전거와 로잉은 종목별 데이터를 사용하고 Garmin과 Apple Watch는 기기 모델을 사용합니다. 안정시 심박수나 5K 시간을 필드 테스트 공식에 넣지 마세요.',
  },
});
