import { createVo2Content } from '../content-factory';

export const content = createVo2Content({
  locale: 'zh', slug: 'vo2-max-calculator', title: '跑步步行和折返跑测试 VO2 max 计算器', description: '根据12分钟跑、1.5英里跑、Rockport一英里步行测试或20米折返跑测试估算 VO2 max，并按年龄和性别参考值进行比较。', faqTitle: 'VO2 max 计算器常见问题', bibliographyTitle: '估算结果背后的三项资料', diagnosticBadge: '值得注意',
  ui: {
    methodCooper12: 'Cooper 12分钟跑', methodCooper15: 'Cooper 1.5英里跑', methodRockport: 'Rockport一英里步行', methodShuttle: '20米折返跑测试', metricUnit: '公制', imperialUnit: '英制', methodLabel: '场地测试', performanceLegend: '记录测试结果', distanceLabel: '12分钟跑步距离', distanceHint: '在测量过的跑道上，用12分钟尽可能跑远。', timeLabel: '测试时间', minutesLabel: '分钟', secondsLabel: '秒', ageLabel: '年龄', sexLabel: '参考性别', maleLabel: '男性', femaleLabel: '女性', weightLabel: '体重', heartRateLabel: '测试结束时心率', stageLabel: '最后完成的阶段', stageHint: '输入从1到21中最后一个完整完成的阶段。', resetButton: '恢复示例', resultTitle: '估算 VO2 max', estimateUnit: '每公斤每分钟氧气毫升数', percentileLabel: '参考区间', referenceTitle: '年龄和性别参考', referenceDescription: '图表是20至79岁成年人的群体参考，不是医学分类。', bandBelow10: '低于第10百分位', band10to25: '第10至25百分位', band25to50: '第25至50百分位', band50to75: '第50至75百分位', band75to90: '第75至90百分位', bandAbove90: '高于第90百分位', methodNoteCooper12: '根据跑步距离计算的 Cooper 估算值。', methodNoteCooper15: '根据1.5英里完成时间计算的估算值。', methodNoteRockport: '根据一英里步行测试计算的 Rockport 估算值。', methodNoteShuttle: '根据最后阶段速度计算的折返跑估算值。', invalidNotice: '填写此测试的字段后即可查看估算值。', safetyNotice: '场地测试是估算，不是临床测量。如果感到不适请停止，并在需要时寻求专业建议。',
  },
  faq: [{ question: '如何根据跑步计算 VO2 max？', answer: '选择 Cooper 12分钟跑并输入跑过的距离，或者选择1.5英里跑并输入完成时间。两种方法都会输出每公斤每分钟氧气毫升数的场地估算值。' }, { question: '如何使用 Cooper VO2 max 计算器？', answer: '在测量过的跑道上用12分钟尽可能跑远，并记录距离。再次测试时使用相同跑道、热身方式和测量方法。' }, { question: '可以通过 Rockport 步行测试计算 VO2 max 吗？', answer: '可以。选择 Rockport 一英里步行，输入时间、体重、年龄、参考性别以及结束时心率。这个协议不能使用静息心率。' }, { question: '这可以作为折返跑测试的 VO2 max 计算器吗？', answer: '可以。选择20米折返跑测试，输入音频测试中最后完整完成的阶段。结果取决于准确距离、节奏和阶段规则。' }, { question: '可以按年龄性别或体重比较 VO2 max 吗？', answer: '输入年龄并选择参考性别，即可将估算值放入参考值中比较。Rockport 公式会使用体重。这个比较提供群体背景，不是诊断。' }, { question: '可以用于骑行划船 Garmin Apple Watch 或静息心率吗？', answer: '第一版暂不支持。这款工具覆盖跑步、步行和20米折返跑。骑行、划船、可穿戴设备和静息心率需要不同的数据与公式。' }],
  howTo: [{ name: '选择匹配的测试', text: '选择与记录结果对应的跑步、步行或折返跑测试协议。' }, { name: '输入测量结果', text: '只有在所选协议需要时，才输入距离、时间、最后阶段、体重和结束心率。' }, { name: '加入年龄和性别背景', text: '输入年龄并选择参考性别，与20至79岁成年人的 FRIEND 参考值进行比较。' }, { name: '重复相同协议', text: '比较下一次估算前，使用相同跑道、单位和测量流程。' }],
  seo: {
    introTitle: '从你已经拥有的 VO2 max 测试开始', introParagraph: '只有知道 VO2 max 数字来自哪里，它才有意义。12分钟跑、一英里步行和折返跑不是可以互换的观察结果。这款计算器保留测试背景，使用对应的估算方法，并提供参考点，而不会把场地测试说成实验室测量。', summaryTitle: '这个计算器能做什么？', summaryItems: ['解读 Cooper 12分钟跑或1.5英里跑的结果。', '估算 Rockport 一英里步行的结果。', '使用20米折返跑最后完成的阶段。', '将20至79岁成年人的年龄和性别放入参考背景。', '建立可重复的基线，追踪自己的变化。'], stats: [{ value: '4', label: '场地测试协议' }, { value: '20至79', label: '参考年龄' }, { value: 'ml/kg/min', label: '共同单位' }], protocolTitle: '先从你测量的事实开始，而不是从公式开始', comparative: [{ title: '你测量了距离', description: '如果记录的是12分钟内跑过多远，就选择 Cooper 12分钟跑。每次使用相同的测量跑道和单位。' }, { title: '你测量了时间', description: '如果记录的是完成距离用了多久，就选择1.5英里跑。5K时间或手表估算属于另一种计算。' }], rockportTitle: '为什么 Rockport 步行测试需要更多背景信息', diagnosticTitle: '把 Rockport 输入看成一个小故事', diagnosticHtml: '<p>步行测试是次最大强度，因此公式需要知道这一英里对你来说有多吃力。</p><ul><li><strong>时间：</strong>完成一英里用了多久。</li><li><strong>结束心率：</strong>到达终点时的心率，而不是静息心率。</li><li><strong>体重、年龄和性别：</strong>公式和参考值使用的背景信息。</li></ul>', ageTitle: '同一个数字在不同年龄可能讲述不同故事', tableHeaders: ['你想知道什么', '图表能告诉你什么', '图表不能告诉你什么'], tableRows: [['估算值位于哪里', '年龄和性别群体中的一个区间。', '你是否健康或达到医学意义上的体适能。'], ['训练是否带来变化', '在相同测试下重复后的趋势。', '如果协议改变，比较是否公平。'], ['是否准备好参加赛事', '体能背景的一部分。', '比赛预测或运动许可。']], shuttleTitle: '折返跑测试中阶段必须结合跑道才有意义', shuttleParagraph: '最后完成的阶段不是通用的体能货币。20米距离、音频、转身方式、地面和阶段规则都很重要。重复相同协议，结果变化才有意义。', listItems: ['<strong>重复同一方法：</strong>用 Cooper 对比 Cooper，不要用跑步对比 Rockport 步行。', '<strong>记录测试条件：</strong>地面、天气、热身和心率测量流程。', '<strong>观察趋势：</strong>单次估算可能有噪声，多次可比测试能讲出更清楚的故事。', '<strong>谨慎使用区间：</strong>这是参考背景，不是对身体的判定。'], tipTitle: '如果你搜索的是骑行划船或运动手表', tipHtml: '那是另一个问题，不是少了一个输入框。骑行和划船使用专项数据，Garmin 和 Apple Watch 使用设备模型。不要把静息心率或5K时间放进场地测试公式。',
  },
});
